// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: LogData.proto

package BaseDatapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogData_LogType int32

const (
	LogData_Normal  LogData_LogType = 0
	LogData_Warning LogData_LogType = 1
	LogData_Error   LogData_LogType = 2
)

// Enum value maps for LogData_LogType.
var (
	LogData_LogType_name = map[int32]string{
		0: "Normal",
		1: "Warning",
		2: "Error",
	}
	LogData_LogType_value = map[string]int32{
		"Normal":  0,
		"Warning": 1,
		"Error":   2,
	}
)

func (x LogData_LogType) Enum() *LogData_LogType {
	p := new(LogData_LogType)
	*p = x
	return p
}

func (x LogData_LogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogData_LogType) Descriptor() protoreflect.EnumDescriptor {
	return file_LogData_proto_enumTypes[0].Descriptor()
}

func (LogData_LogType) Type() protoreflect.EnumType {
	return &file_LogData_proto_enumTypes[0]
}

func (x LogData_LogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogData_LogType.Descriptor instead.
func (LogData_LogType) EnumDescriptor() ([]byte, []int) {
	return file_LogData_proto_rawDescGZIP(), []int{0, 0}
}

type LogData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type LogData_LogType `protobuf:"varint,1,opt,name=type,proto3,enum=BaseData.LogData_LogType" json:"type,omitempty"` //日志类型
	Msg  []byte          `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                                  //日志的具体消息
}

func (x *LogData) Reset() {
	*x = LogData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LogData_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogData) ProtoMessage() {}

func (x *LogData) ProtoReflect() protoreflect.Message {
	mi := &file_LogData_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogData.ProtoReflect.Descriptor instead.
func (*LogData) Descriptor() ([]byte, []int) {
	return file_LogData_proto_rawDescGZIP(), []int{0}
}

func (x *LogData) GetType() LogData_LogType {
	if x != nil {
		return x.Type
	}
	return LogData_Normal
}

func (x *LogData) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

var File_LogData_proto protoreflect.FileDescriptor

var file_LogData_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x42, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x79, 0x0a, 0x07, 0x4c, 0x6f, 0x67,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x2d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x19, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x4c, 0x6f,
	0x67, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x4c, 0x6f, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x2d, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07,
	0x57, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x10, 0x02, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x42, 0x61, 0x73, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_LogData_proto_rawDescOnce sync.Once
	file_LogData_proto_rawDescData = file_LogData_proto_rawDesc
)

func file_LogData_proto_rawDescGZIP() []byte {
	file_LogData_proto_rawDescOnce.Do(func() {
		file_LogData_proto_rawDescData = protoimpl.X.CompressGZIP(file_LogData_proto_rawDescData)
	})
	return file_LogData_proto_rawDescData
}

var file_LogData_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_LogData_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_LogData_proto_goTypes = []interface{}{
	(LogData_LogType)(0), // 0: BaseData.LogData.LogType
	(*LogData)(nil),      // 1: BaseData.LogData
}
var file_LogData_proto_depIdxs = []int32{
	0, // 0: BaseData.LogData.type:type_name -> BaseData.LogData.LogType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_LogData_proto_init() }
func file_LogData_proto_init() {
	if File_LogData_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_LogData_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_LogData_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_LogData_proto_goTypes,
		DependencyIndexes: file_LogData_proto_depIdxs,
		EnumInfos:         file_LogData_proto_enumTypes,
		MessageInfos:      file_LogData_proto_msgTypes,
	}.Build()
	File_LogData_proto = out.File
	file_LogData_proto_rawDesc = nil
	file_LogData_proto_goTypes = nil
	file_LogData_proto_depIdxs = nil
}
