// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: TopData.proto

package TrZeroMQMsgpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//检索的类型
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	//序列化后的类
	RawData []byte `protobuf:"bytes,2,opt,name=rawData,proto3" json:"rawData,omitempty"`
}

func (x *TopData) Reset() {
	*x = TopData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TopData_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopData) ProtoMessage() {}

func (x *TopData) ProtoReflect() protoreflect.Message {
	mi := &file_TopData_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopData.ProtoReflect.Descriptor instead.
func (*TopData) Descriptor() ([]byte, []int) {
	return file_TopData_proto_rawDescGZIP(), []int{0}
}

func (x *TopData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TopData) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

var File_TopData_proto protoreflect.FileDescriptor

var file_TopData_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x54, 0x6f, 0x70, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x54, 0x72, 0x5a, 0x65, 0x72, 0x6f, 0x4d, 0x51, 0x4d, 0x73, 0x67, 0x22, 0x37, 0x0a, 0x07,
	0x54, 0x6f, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72,
	0x61, 0x77, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x72, 0x61,
	0x77, 0x44, 0x61, 0x74, 0x61, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x54, 0x72, 0x5a, 0x65, 0x72,
	0x6f, 0x4d, 0x51, 0x4d, 0x73, 0x67, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_TopData_proto_rawDescOnce sync.Once
	file_TopData_proto_rawDescData = file_TopData_proto_rawDesc
)

func file_TopData_proto_rawDescGZIP() []byte {
	file_TopData_proto_rawDescOnce.Do(func() {
		file_TopData_proto_rawDescData = protoimpl.X.CompressGZIP(file_TopData_proto_rawDescData)
	})
	return file_TopData_proto_rawDescData
}

var file_TopData_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TopData_proto_goTypes = []interface{}{
	(*TopData)(nil), // 0: TrZeroMQMsg.TopData
}
var file_TopData_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_TopData_proto_init() }
func file_TopData_proto_init() {
	if File_TopData_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_TopData_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TopData_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TopData_proto_goTypes,
		DependencyIndexes: file_TopData_proto_depIdxs,
		MessageInfos:      file_TopData_proto_msgTypes,
	}.Build()
	File_TopData_proto = out.File
	file_TopData_proto_rawDesc = nil
	file_TopData_proto_goTypes = nil
	file_TopData_proto_depIdxs = nil
}
